site_name: SysEleven Stack Documentation
theme_dir: custom_yeti_theme
google_analytics: ['UA-4634575-5', 'doc.cloud.syseleven.net']
repo_name: "GitHub"
repo_url: "https://github.com/syseleven/syselevenstack-documentation"

pages:
  - index.md
  - 'Tutorials': 
    - 'Erste Schritte': 'tutorials/01-firststeps.md'
    - 'API-Zugriff': 'tutorials/02-kickstart.md'
    - 'Server in Gruppen organisieren': 'tutorials/03-servergruppen.md'
    - 'Minimal CoreOS environment': 'tutorials/04-coreos.md'
  - 'Dokumentation':
    - 'Compute': 'dokumentation/compute.md'
    - 'Networking': 'dokumentation/networking.md'
    - 'Block Storage': 'dokumentation/block-storage.md'
    - 'Object Storage': 'dokumentation/object-storage.md'
    - 'Orchestration': 'dokumentation/orchestration.md'

copyright: SysEleven Stack is made with ♥ in Berlin.<br/>
    For further questions, don't hesitate to contact us at <a href="mailto:cloudsupport@syseleven.de">cloudsupport@syseleven.de</a>
